{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ required "You must define the .Values.assetId value!" .Values.assetId }}-stellar-vanity-coin
  labels:
    {{- include "stellar-vanity-coin.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
